import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const sansation = localFont({
  src: "../public/fonts/Sansation-Bold.ttf",
  variable: "--font-sansation",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Ideate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.variable} ${sansation.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
